### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by wolfkdy** [heiyeluren/go-tmlog#1]
FlushLogChan 结构体是new出来的，这个管道没有初始化，往一个没有初始化的管道里发数据是会blocking的。因此每次触发这句threshold = float32(curr_chan_len) / float32(G_Log_V.LogChanBuffSize)的goroutine都会hang住。

btw，你这个代码也写的太渣了，FlushLogChan 管道你都没有用到，留着干啥

**Comment by heiyeluren** [comment]
感谢你的意见~
